on:
  push:
    branches: [ main ]
    paths:
      - 'bin/**'
      - 'test/**'
      - 'lib/**'
      - 'pubspec.yaml'
      - 'pubspec.lock'
      - 'action.yml'
      - 'Dockerfile'
      - '.github/workflows/main.yml'
  pull_request:
    branches: [ main ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to compile linux/arm64 dart executable
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      
      # compile dart
      - name: Compile dart linux/arm64 action step
        uses: ./ # Uses an action in the root directory
        id: compile
        with:
          dart_main_file: 'bin/main.dart'
          dart_compiled_file: 'linux-arm64.exe'

      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "Compile result is ${{ steps.compile.outputs.my_console_output }}"

      # Upload artifact
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: /var/lib/docker/volumes/sfsd/_data